version: "3.0"
name: "mountain-app"
services:
  managers:
    image: freddy153/ventura-boulevard:latest-deployment
    container_name: managers
    restart: unless-stopped
    ports:
      - 8080:8080
    depends_on:
      - db
    networks:
      - shared-net

  gateway:
    image: freddy153/radio-nowhere:latest-deployment
    container_name: gateway
    restart: unless-stopped
    ports:
      - "8085:8085"
    networks:
      - shared-net
    depends_on:
      - managers
    expose:
      - "8085"

  frontend:
    image: freddy153/zombie-zoo:latest-deployment
    container_name: frontend
    restart: unless-stopped
    depends_on:
      - gateway
    networks:
      - shared-net
    ports:
      - "9000:9000"
    expose:
      - "9000"

  db:
    image: postgres
    container_name: postgres
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: test_db
    ports:
      - "5432:5432"
    expose:
      - "5432"
    networks:
      - shared-net

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    depends_on:
      - db
    ports:
      - "5050:80"
    networks:
      - shared-net

  watchtower-autoupdate:
    image: containrrr/watchtower
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: --interval 86400 --cleanup --remove-volumes --include-restarting --log-format Pretty

  watchtower-manualupdate:
    image: containrrr/watchtower
    container_name: manual-update
    depends_on:
      watchtower-autoupdate:
        condition: service_completed_successfully
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: --run-once --cleanup --remove-volumes --include-restarting --log-level info --log-format Pretty

networks:
  shared-net:
