version: "3.0"
name: "mountain-app"
services:
  managers:
    image: freddy153/ventura-boulevard:latest-deployment
    container_name: managers
    restart: unless-stopped
    # Rimuovere i segiuenti due commenti se si vuole accedere dall'esterno direttamente ai manager
    # ports:
    #   - 8080:8080
    depends_on:
      db:
        condition: service_healthy

  gateway:
    image: freddy153/radio-nowhere:latest-deployment
    container_name: gateway
    restart: unless-stopped
    ports:
      - "8085:8085"
    depends_on:
      - managers

  frontend:
    image: freddy153/zombie-zoo:latest-deployment
    container_name: frontend
    restart: unless-stopped
    depends_on:
      - gateway
    ports:
      - "9000:9000"

  db:
    image: postgres
    container_name: postgres
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: test_db
    healthcheck:
      test:
        [
          "CMD",
          "pg_isready",
          "-q",
          "-d",
          "postgres",
          "-U",
          "root"
        ]
      timeout: 45s
      interval: 10s
      retries: 10
    volumes:
      - ./Backend/Iterazione3/dbinit:/docker-entrypoint-initdb.d/

  # Tool per la gestione del DB attraverso UI
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "5050:80"

  # Updater automatico
  watchtower-autoupdate:
    image: containrrr/watchtower
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: --interval 86400 --cleanup --remove-volumes --include-restarting --log-format Pretty

  # Updater manuale
  watchtower-manualupdate:
    image: containrrr/watchtower
    container_name: manual-update
    depends_on:
      watchtower-autoupdate:
        condition: service_completed_successfully
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: --run-once --cleanup --remove-volumes --include-restarting --log-level info --log-format Pretty
