name: mountain_app
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  http: ^1.2.0
  intl: ^0.19.0
  lottie: ^3.0.0
  flutter_launcher_icons: "^0.13.1"
  build_runner: ^2.4.0
  build_web_compilers: ^4.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "images/icon.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
  web:
    generate: true
    image_path: "images/icon.png"
    background_color: "#hexcode"
    theme_color: "#hexcode"
  windows:
    generate: true
    image_path: "images/icon.png"
    icon_size: 48 # min:48, max:256, default: 48
  macos:
    generate: true
    image_path: "images/icon.png"

flutter:
  uses-material-design: true
  assets:
    - images/
    - assets/
  fonts:
    - family: comfortaa
      fonts:
        - asset: fonts/Comfortaa/Comfortaa-VariableFont_wght.ttf